SELECT
    c.ID AS CUSTOMER_ID,
    c.USERNAME,
    COUNT(a.ID) AS ACCOUNT_COUNT,
    COALESCE(SUM(a.BALANCE), 0) AS TOTAL_BALANCE
FROM CUSTOMER c
LEFT JOIN ACCOUNT a ON a.CUSTOMER_ID = c.ID
WHERE c.ID = ?
GROUP BY c.ID, c.USERNAME
